#%RAML 1.0 DataType
description: Error message data type
type: object
properties:
  errorCode:
    description: Error code for the error
    required: true
    type: string
    example: '50001'
  message:
    description: Display message for the error
    required: true
    type: string
    example: 'Customer cannot be created'
  errorDetail:
    description: Detailed error message with technical details
    required: false
    type: string
    example: 'Cannot connect to database'

example:
  { 
      "errorCode" : "50001",
      "message" : "Cannot access customer record",
      "errorDetail" : "Error connecting to database"
  }